const language_en = {
	"주차별 설명 보기":"description by week",
	"카카오톡 내부에서는 구글 계정 로그인에 실패할 수 있습니다." : "You may fail to log into your Google account inside KakaoTalk.",
	"크롬으로 열기" : "Open with chrome",
	"URL복사하기" : "Copy URL",
	"출산예정일" : "Due Date",
	"출산일이 아닌 출산 예정일 기준" : "Based on the due date, not the birth date",
	"오늘은 원더윅스입니다." : "Today is wonder weeks.",
	"오늘은 원더윅스가 아닙니다." : "Today is not wonder weeks.",
	"구글 계정 로그인하고 캘린더에 추가하기" : "Log in to add Wonder Weeks Calendar",
	"구글 캘린더에 추가하기" : "Add to Google Calendar",
	"로그아웃" : "Log out",
	"과거 달력 보이기" : "Show past calendar",
	"과거 달력 숨기기" : "Hide past calendar",
	"이 시기에는" : "At this time",
	"수면에 대해" : "About sleep",
	"올바른 출산 예정일을 선택해주세요!" : "Please choose the correct due date!",
	"맥/아이폰 캘린더에 추가하기" : "Add to Mac/Iphone Calendar",
	"원더 윅스 주차별 설명은 babysleepsite.com을 참고했습니다." : "Wonder Weeks explanations are from babysleepsite.com.",
	"이 웹페이지는 구글 계정과 개인 일정에 관련한 어떤 정보도 수집하거나 저장하지 않습니다." : "This webpage does not collect or store any information related to your Google account and calendar.",
	"추가되었습니다!":"finish!",
	"1월" : "January",
	"2월" : "February",
	"3월" : "March",
	"4월" : "April",
	"5월" : "May",
	"6월" : "June",
	"7월" : "July",
	"8월" : "August",
	"9월" : "September",
	"10월" : "October",
	"11월" : "November",
	"12월" : "December",
	"[5주] 감각의 변화" : "[5 weeks] Changing Sensations",
	"[8-9주] 패턴의 생성" : "[8-9 weeks] Patterns",
	"[12주] 자연스러운 움직임" : "[12 weeks] Smooth Transitions",
	"[15-19주] 이벤트" : "[15-19 weeks] Events",
	"[23-26주] 관계 형성" : "[23-26 weeks] Relationships",
	"[33-37주] 분류 인지" : "[33-37 weeks] Categories",
	"[42-46주] 순서 인지" : "[42-46 weeks] Sequences",
	"[52-55주] 유아기 시작" : "[52-55 weeks] Programs",
	"[61-64주] 원칙" : "[61-64 weeks] Principles",
	"[72-76주] 시스템" : "[72-76 weeks] Systems",
	"아기가 '깨어나서' 더이상 엄마의 뱃속이 아님을 깨닫고 더 주변을 살피게 됩니다. 아기에겐 엄청난 변화입니다!" : "Your newborn is “waking up”, becoming more alert, and noticing the world around her. This is understandably overwhelming for newborns!",
	"아기가 단순한 패턴을 반복하기 시작합니다. 같은 방법으로 손을 움직이는걸 연습하거나 끙끙거리는 소리 내기를 반복합니다." : "Baby is beginning to recognize and create simple patterns in his world; he’ll practice moving his hands in the same way over and over, or make the same grunting sound again and again.",
	"아기의 움직임이 부드럽고 정교해집니다. 아기는 주변 환경의 변화와 이런 변화의 일정한 패턴을 파악하게 됩니다. (초인종이 울리면 엄마가 방을 나간다거나)" : "Baby’s movements become smoother and more coordinated; baby also begins to recognize changes in her world, and the patterns of these changes (i.e. every time the dryer buzzer goes off, mom leaves the room).",
	"아기가 원인과 결과를 인식하고 예측하는 법을 배웁니다. 예를들면 장난감을 떨어뜨리면 장난감이 바닥으로 떨어지게되고 아빠가 와서 집어준다는걸 알게 되죠." : "Baby is learning to recognize cause and effect, and to predict outcomes (i.e. ‘If I drop this toy, it will fall to the ground, and dad will come and pick it up’).",
	"아기가 멀리까지 보게 됩니다. 아기에게 세상이 더 큰 공간이 됩니다. 많은 아기들이 이 시기에 더 구르기 시작하는 이유입니다." : "Baby begins to perceive distance at this point – the world becomes a much bigger place for her! This may be one reason why many babies begin rolling/crawling at this time.",
	"여러가지가 함께 분류될수 있음을 배우고 있습니다. 예를들어 블록들이 모양은 모두 다르지만 모두가 블록이라는것을 인지하게 됩니다. 아기가 기어다니는 법을 배우게 됩니다. 일어서기 위해 뭔가를 잡아 당기고 발걸음을 딛기 위해 노력합니다." : "Baby is learning that various things can be grouped together – for example, his blocks may all look different, but he recognizes that they are all blocks. Baby also makes big strides in mobility, learning to crawl well, to pull up to standing, and possibly to take assisted steps.",
	"아기가 옷을 입거나 점심을 만들거나 하는 간단한 작업과 관련된 순서들을 인식하게 됩니다. 가령 아기는 양말을 신발보다 먼저 신어야 한다는것을 알게됩니다." : "Baby begins recognizing the steps involved in simple tasks, like getting dressed, or making lunch. Baby can also apply this to his own tasks – socks have to go on before shoes.",
	"아기가 어떤 일을 할 때 여러가지 방법이나 순서가 있다는걸 알게됩니다. 대부분의 아기들이 강한 선호도를 보이기 시작합니다. (분홍 양말은 좋고 녹색 양말은 싫다거나)" : "Your toddler builds on his understanding of sequences, and starts to learn that there is more than one way (or one “sequence”) to accomplish the same task. This is also when most toddlers start showing strong preferences (i.e. pink socks are great, but green socks are bad).",
	"생후 4개월쯤 배웠던 인과관계와 관련이 있는 시기입니다. 아기가 목표를 달성하기 위해 인과관계를 사용하는 방법을 배웁니다. 아기가 한 행동이 특정한 결과를 만들게 된다는걸 배우게 됩니다." : "This stage is related to the cause-and-effect breakthrough we saw in the 15-19 week stage, only now, your toddler is learning how to use cause-and-effect to achieve her goals. She is also learning that her actions have certain consequences",
	"아기가 더 큰 시스템을 이해하게 됩니다. 예를들어 어린이집에서의 행동하는 절차와 기대치가 집에서는 다르다는것을 알고 있습니다. 아기는 상황에 맞게 스스로의 행동을 바꿀 수 있습니다. 육아도우미분에겐 친절하게 대하다가 엄마에겐 심술궂게 대할수 있습니다." : "Your toddler is capable of understanding larger systems now – for instance, she knows that the procedures and expectations at daycare are different than those at home. Your toddler can also change her behavior and actions to suit different situations, which explains why your toddler may be sweet and helpful for the babysitter, but grumpy and whiny for you (which is not at all uncommon, by the way!).",
	"엄마를 힘들게 하는 '마녀의 시간(오후 5시에서 10~11시까지)'이 시작됩니다. 아기를 더 자주 껴안아주어야 합니다.(아기띠를 메는것도 좋아요.) 밤에 더 자주 먹이게 되고 때때로 아기가 토를 하기도 합니다. 6주차까지 수면의 어려움을 겪기도합니다." : "This is when “the witching hour” usually starts – that period of fussiness from about about 5 – 10 or 11 p.m. Be available to cuddle baby often (wearing baby is a great idea at this time); you may also need to feed more frequently in the evening. Baby may also go through a growth spurt at this time. Finally, keep in mind that this wonder week overlaps a bit with the 6 week peak of fussiness.",
	"아기의 호기심과 주의력으로 인해 아기가 잠드는것이 어려울수 있습니다. 아기가 자는 공간을 잠들기 쉽게 어둡고 조용하게 만들어주세요." : "All this curiosity and alertness can make it hard for baby to settle and fall sleep, so be sure to make your nursery sleep-friendly – it should be dim and quiet. This is also a great time to begin working on simple sleep time routines – start doing the same patterns of events at nap time and bedtime.",
	"아기가 꿈틀거리기 시작하고 더 활동적이게 됩니다. 수면 루틴이 변할수도 있음을 의미합니다. 속싸개를 풀어주어도 좋습니다. 아기가 뒤집기 시작하면 수면을 방해하게 됩니다. 아기는 바닥에 등을 대고 있다가 배로 뒤집을수 있지만 반대로는 하지 못합니다. 몇몇 아기들은 통잠을 자게 되기도 하고 수유텀이 일정해집니다." : "Baby is getting squirmier at this age, and becoming more active – and that can mean changes to your sleep routine. Your baby may start breaking free of the swaddle. Some parents find that baby’s newfound ability to roll interferes with sleep – baby can roll from back to tummy, but not the other way around. Other parents notice that their babies settle into a semi-regular sleeping and feeding schedule at this age.",
	"4개월이 되면 수면 습관이 다시 깨질수 있습니다.(수면 회귀) 지금까지 아기의 수면 패턴을 예측할수 있었다면 전부 깨질 수 있습니다. 일정한 수면 습관을 들일수 있도록 노력해야 합니다. 수면 습관을 통해 어떤 행동이 잠으로 이어지는지 아기가 알수 있도록 훈련해야 합니다. 아이가 급성장하는 시기입니다." : "Welcome to the 4 month sleep regression! If baby’s sleep was predictable up to this point, it may all fall apart now. Continue to work on building consistent sleep routines; this will help baby learn that certain events mean sleep is coming. You may also want to work on identifying any sleep associations baby may have; that will help with sleep training. There’s also another growth spurt that happens around 4 months.",
	"분리불안이 낮잠을 자거나 밤잠을 잘 때 문제가 되기도합니다. 엄마가 아기 곁을 떠날 때 엄마가 멀리 가버린다는걸 알게되기 때문입니다. 아기에게 수면 교육을 할 수 있는 좋은 때이기도 합니다. 아기가 독립적으로 잠드는 방법을 배우도록 도와주세요. 대부분의 아이들은 이 시기에 다시 급성장하게 됩니다." : "Separation anxiety may become a problem at nap time and bedtime, since baby now understands that when you leave, you’re far away. This is also a great time to sleep train your baby – work on weaning your baby away from her sleep associations, and on helping her learn to fall asleep independently. Finally, there’s yet another growth spurt that happens around 6 months, for most babies.",
	"스스로 이동할 수 있게 되면서 수면에 심각하게 방해가 됩니다. 아기가 수면 시간에 울면 엄마가 어떻게 행동할지 패턴을 알아차리게 되므로 이 때에 다른 수면습관을 배우지 않게 조의해야 합니다. 아기가 밤에 깨어있을 때 수유를 하지 않는것이 좋습니다. 그리고 9개월차는 또 다른 급성장 시기입니다." : "This Wonder Week coincides with the 8/9/10 month sleep regression. Baby’s sleep may be seriously disrupted, thanks to all his new-found mobility. But baby may also begin to experiment with cause and effect at sleep times – ‘If I cry, what will mom do?’ Your baby will quickly pick up on any patterns, so make sure not to create any new sleep associations at this stage. Finally, if baby is still waking to feed at night at this age, we usually recommend an attempt at night-weaning. (Oh, and P.S. – there is (you guessed!) another growth spurt to watch out for, around 9 months.)",
	"루틴은 이 단계에서 매우 중요합니다. 대부분의 아이들은 다음에 어떤일이 올지 아는것을 좋아합니다. 그래서 수면 습관을 강화하기 좋습니다. 이 시기에 부모들이 짧게 수면 회귀를 겪고 오전에 낮잠재우는걸 포기하기도 합니다. 아기에게 낮잠은 한번만으로는 부족하므로 두번재울수 있게 노력하세요. " : "Routines are so key at this stage; most babies love knowing what comes next, so work to continue strengthening your sleep routines. You may find that your baby goes through the brief 12 month sleep regression around this time, and tries to give up her morning nap; we advise that you stick to two naps for now, as most babies this age can’t manage with just one nap.",
	"유아기에 온걸 환영합니다! 이 단계에서 분리불안이 다시 찾아옵니다. 아기가 자신의 독립성과 스스로 선호하는것을 주장하면서 낮잠을 자거나 밤잠을 자는것에 반항하게 될 수 있습니다." : "Welcome to toddlerhood, parents! At this stage, separation anxiety often comes back with a vengeance. You may also start to see some nap time and bedtime resistance at this point, as your toddler is learning to assert his independence and preferences.",
	"징계에 대해 생각해볼 시기입니다. 아기가 자신의 행동에 부모가 어떻게 반응하는지 빠르게 배우고 있으므로 아기에게 반응할때 올바른 메시지를 전달하도록 노력해야 합니다. 수면에 대해서는 아기에게 경계를 설정하고 제한해야하는 시기입니다. 이 시기의 수면에 대한 문제는 수면의 문제가 아니고 징계의 문제라고 이야기 합니다." : "It’s time to talk about the D-word, parents – discipline. Your toddler is learning fast how you respond to her actions, so be sure that you are sending the right messages with your responses. This is the time to start establishing boundaries and setting limits for your toddler surrounding sleep, and enforcing them. We often tell parents that at this age, sleep problems are rarely sleep problems – they are discipline problems.",
	"유아로서의 특성이 많이 드러납니다. 아기의 수면 시간을 지키도록 노력해야합니다. 17~18개월엔 보통 짜증을 많이 냅니다. 낮잠이나 밤잠 시간에 특히 짜증을 많이 내서 부모를 힘들게합니다. 이 때 흔들리지 않는것이 중요합니다. 수면 회귀를 가장 심하게 겪을 수 있습니다." : "If it hasn’t already, your toddler’s ‘toddler attitude’ may show itself full-force around this time. Continue to enforce your sleep time boundaries and limits. By 17 or 18 months, tantrums are common. Toddler tantrums at bedtime and nap time are especially frustrating – it’s key that you stand firm during these tantrums. Also, watch for the 18 month sleep regression that happens at about this time; it tends to be one of the toughest.",
}